sudo: false
language: python
install: true
script: py.test
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: vecnet
  password:
    secure: P6zKZHjUc/cFxdE1gYMx00NfShFFKdiZ9lDcMdP9Fk7d1chWId052De3n9boP8FcxJvqhMHf9GqM5Drmxk3rHtFBCDUcHPpFYQu3KOOejuMh3a3E748tQ8cNxv/R1X9bLQb8lc+m1/akO9U4xSppbypee7Xc7feIUGC/w4kHNDc=
  on:
    all_branches: true
    tags: true
